apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: updater
customVersion: v1beta2
spec:
  v1beta2:
    image: libsysguy/habitat-updater:0.0.1-20180423205849
    count: 1
    service:
      name: habitat-updater
      topology: standalone
